fix setting add models
yuriao/FLAG-Camp-team1-Community-Management pull request #9
Opened 2020-09-21 18:52 UTC by tcchenbtx

fix backend setting add TicketComments & TicketWorkAssignee models

2020-09-21 23:54 UTC, yunjinwu requested changes

2020-09-21 23:54 UTC, yunjinwu commented on communitymanagement/src/main/java/communitymanagement/model/TicketComments.java
> +	@ManyToOne
apply to all: different indentions --  not a big deal though but if we could make code prettier that'll be great

2020-09-22 01:01 UTC, tcchenbtx commented on communitymanagement/src/main/java/communitymanagement/model/TicketComments.java
> +	@ManyToOne
good catch! :)

2020-09-22 01:04 UTC, yunjinwu approved these changes

2020-09-22 01:06 UTC, merged